Repository DevCo-ops/Devocidy, pull requests merged in 2021-04, with the labels that each got.

#31 Fix refresh
  Containers/group-list.js
  Containers/group.js
  components/Goups/group-head.js
  components/MUI/theme.js
  components/UI/Button.js
  components/UI/LogoLink.js
  components/UI/NavTab.js
  components/UI/Smooth.js
  components/UI/progress.js
  components/layout/NavBar.js
  pages/groups/[id].js
Labels: UI, bug

#33 Update README.md
  README.md
Labels: documentation

#41 Test
  README.md
  package-lock.json
Labels: documentation

#35 Update issue templates
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#53 Hurly77 group route
  Containers/group.js
  components/GroupPage/group-body.js
  components/GroupPage/group-nested-routes.js
  components/MUI/theme.js
  components/UI/ContainerBox.js
  components/UI/NavTab.js
  jsconfig.json
Labels: UI, UX

#52 Remove duplicate GitHub template
  .env.local.sample
  .github/ISSUE_TEMPLATE/1.bug.md
  .github/ISSUE_TEMPLATE/2.feature.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: bug, config

#45 Add crud to api
  pages/api/groups/[id].js
  pages/api/groups/index.js
  pages/api/users/[id].js
  pages/api/users/index.js
  utils/dbConnect.js
Labels: API, bug, enhancement

#61 Hurly77 group route
  Containers/group.js
  components/GroupPage/group-body.js
  components/GroupPage/group-nested-routes.js
  components/GroupSlugs/console.js
  components/GroupSlugs/content.js
  components/GroupSlugs/users.js
  components/UI/Button.js
  jsconfig.json
  pages/groups/[...slug].js
  pages/groups/[id].js
  pages/groups/[id]/console.js
  pages/groups/[id]/index.js
  pages/groups/[id]/users.js
Labels: UI, UX, duplicate

#57 Hurly77 group route
  Containers/group.js
  components/GroupPage/group-body.js
  components/GroupPage/group-nested-routes.js
  components/GroupSlugs/console.js
  components/GroupSlugs/content.js
  components/GroupSlugs/users.js
  components/MUI/theme.js
  components/UI/Button.js
  components/UI/ContainerBox.js
  components/UI/NavTab.js
  jsconfig.json
  pages/groups/[...slug].js
  pages/groups/[id].js
  pages/groups/[id]/console.js
  pages/groups/[id]/index.js
  pages/groups/[id]/users.js
Labels: UI, UX, config

#62 Hurly77 group route
  Containers/Layout.js
  Containers/group-list.js
  Containers/group.js
  README.md
  components/Goups/group-card.js
  components/Goups/group-description.js
  components/Goups/group-head.js
  components/Goups/group-media.js
  components/GroupPage/group-body.js
  components/GroupPage/group-nested-routes.js
  components/GroupSlugs/console.js
  components/GroupSlugs/content.js
  components/GroupSlugs/users.js
  components/MUI/theme.js
  components/UI/Button.js
  components/UI/ContainerBox.js
  components/UI/NavTab.js
  components/layout/Contributors.js
  components/layout/Footer.js
  components/layout/NavBar.js
  jsconfig.json
  models/Group.js
  models/User.js
  package-lock.json
  pages/_app.js
  pages/_document.js
  pages/groups/[...slug].js
  pages/groups/[id].js
  pages/groups/[id]/console.js
  pages/groups/[id]/index.js
  pages/groups/[id]/users.js
  pages/groups/index.js
  pages/index.js
Labels: UI, UX

#63 Revert "Hurly77 group route"
  Containers/Layout.js
  Containers/group-list.js
  Containers/group.js
  README.md
  components/Goups/group-card.js
  components/Goups/group-description.js
  components/Goups/group-head.js
  components/Goups/group-media.js
  components/GroupPage/group-body.js
  components/GroupPage/group-nested-routes.js
  components/GroupSlugs/console.js
  components/GroupSlugs/content.js
  components/GroupSlugs/users.js
  components/MUI/theme.js
  components/UI/Button.js
  components/UI/ContainerBox.js
  components/UI/NavTab.js
  components/layout/Contributors.js
  components/layout/Footer.js
  components/layout/NavBar.js
  jsconfig.json
  models/Group.js
  models/User.js
  package-lock.json
  pages/_app.js
  pages/_document.js
  pages/groups/[...slug].js
  pages/groups/[id].js
  pages/groups/[id]/console.js
  pages/groups/[id]/index.js
  pages/groups/[id]/users.js
  pages/groups/index.js
  pages/index.js
Labels: UI, UX

#64 Update module path aliases
  Containers/Layout.js
  Containers/group-list.js
  Containers/group.js
  pages/_app.js
  pages/_document.js
  pages/api/auth/[...nextauth].js
  pages/api/groups/[id].js
  pages/api/groups/index.js
  pages/api/users/[id].js
  pages/api/users/index.js
  pages/groups/index.js
Labels: bug, config, duplicate, enhancement

#50 add documentation to module path aliases
  CONTRIBUTING.md
Labels: documentation

#66 Update configuration of redux
  models/Group.js
  package.json
  pages/_app.js
  pages/api/groups/[id].js
  pages/api/groups/index.js
  pages/groups/index.js
  store/groups/actions.js
  store/groups/reducer.js
  store/index.js
  store/users/actions.js
  store/users/reducer.js
Labels: API, Redux, config, enhancement

#72 Update users redux actions and reducer
  models/User.js
  pages/api/auth/[...nextauth].js
  pages/api/users/[id].js
  pages/api/users/index.js
  store/users/actions.js
  store/users/reducer.js
  utils/dbConnect.js
Labels: API, DB, Redux, bug, enhancement

#70 Update groups' redux actions and reducer
  pages/api/groups/[id].js
  store/groups/actions.js
  store/groups/reducer.js
Labels: API, Redux

#73 Redux update/add conditional dispatch
  store/groups/actions.js
  store/groups/reducer.js
  store/users/actions.js
  store/users/reducer.js
Labels: Redux, enhancement
